services:
  caddy:
    image: ${MY_CADDY_IMAGE:-caddy:2-alpine}
    restart: unless-stopped
    ports:
    - 8443:443
    - 8080:80
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile:ro
    - ./certs/tls.crt:/etc/caddy/certs/tls.crt:ro
    - ./certs/tls.key:/etc/caddy/certs/tls.key:ro
    depends_on:
    - management
    - signal
    - zitadel
    - dashboard
    healthcheck:
      test:
      - CMD
      - caddy
      - version
      interval: 30s
      timeout: 3s
      retries: 3
  management:
    ports: []
    dns:
      - 8.8.8.8
      - 1.1.1.1
  signal:
    ports:
    - 10000:10000
  dashboard:
    ports: []
    environment:
      NETBIRD_MGMT_API_ENDPOINT: https://${NETBIRD_DOMAIN}:8443
      NETBIRD_MGMT_GRPC_API_ENDPOINT: https://${NETBIRD_DOMAIN}:8443
      NEXT_PUBLIC_NETBIRD_MGMT_API_ENDPOINT: https://${NETBIRD_DOMAIN}:8443
      NEXT_PUBLIC_NETBIRD_MGMT_GRPC_API_ENDPOINT: https://${NETBIRD_DOMAIN}:8443
      AUTH_AUTHORITY: https://${NETBIRD_DOMAIN}:8443
      AUTH_CLIENT_ID: '376317538281193476'
      AUTH_AUDIENCE: '376317538281193476'
      NEXT_PUBLIC_AUTH_AUTHORITY: https://${NETBIRD_DOMAIN}:8443
      NEXT_PUBLIC_AUTH_CLIENT_ID: '376317538281193476'
      NEXT_PUBLIC_AUTH_AUDIENCE: '376317538281193476'
      AUTH_SUPPORTED_SCOPES: openid profile email offline_access
      AUTH_REDIRECT_URI: /nb-auth
      AUTH_SILENT_REDIRECT_URI: /nb-silent-auth
      AUTH_BASE_URL: https://${NETBIRD_DOMAIN}:8443
      AUTH_POST_LOGOUT_REDIRECT_URI: /
      USE_AUTH0: 'false'
    extra_hosts:
      - "${NETBIRD_DOMAIN}:host-gateway"
  coturn:
    deploy:
      replicas: 0
  zitadel:
    ports:
    - 8081:8080
